DROP TABLE "STATE";
DROP TABLE "CITY";
DROP SEQUENCE STATE_SEQUENCE;


CREATE TABLE "STATE"
(
	"ID_STA" NUMBER(19,0),
	"UF" VARCHAR2(255 CHAR),
	CONSTRAINT PK_STATE PRIMARY KEY (ID_STA)
);

CREATE TABLE "CITY"
(
	"IBGE_ID" NUMBER(19,0) NOT NULL,
	"ID_STA" NUMBER(19,0),
	"LONG" NUMBER(19,10),
	"LAT" NUMBER(19,10),
	"NAME" VARCHAR2(255 CHAR),
	"CAPITAL" VARCHAR2(255 CHAR),
	"NO_ACCENTS" VARCHAR2(255 CHAR),
	"ALTERNATIVE_NAMES" VARCHAR2(255 CHAR),
	"MICRO_REGION" VARCHAR2(255 CHAR),
	"MESO_REGION" VARCHAR2(255 CHAR),
	CONSTRAINT PK_CITY PRIMARY KEY (IBGE_ID)
);



CREATE SEQUENCE state_sequence;

CREATE OR REPLACE TRIGGER state_on_insert
  BEFORE INSERT ON state
  FOR EACH ROW
BEGIN
  SELECT state_sequence.nextval
  INTO :new.ID_STA
  FROM dual;
END;